default_lang: en
author:
  name: 'Scope Web Team'
  email: info@scopeweb.nyc
taxonomies:
  - tag
  - featured
metadata:
  description: 'Your website in just one week. Scope Web builds professional and highly performant online web platforms. Using the latest innovation in web design, we provide the next-generation of succesfull businesses with a strong online presence. We do everything possible to make your organization more successful!'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
title: Scope Web
